In [8]:
import pandas as pd

In [9]:
df=pd.DataFrame({
    "id":[1,2,3,4],
    "color":["red","blue","green","red"],
    "size":["small","medium","large","medium"],
    "price":[10,12,15,11]
})
df

   id  color    size  price
0   1    red   small     10
1   2   blue  medium     12
2   3  green   large     15
3   4    red  medium     11

In [10]:
order={"small":1,"medium":2,"large":3}

In [11]:
# create new colum

df["size_encoded"]=df["size"].map(order).astype(int)
df

   id  color    size  price  size_encoded
0   1    red   small     10             1
1   2   blue  medium     12             2
2   3  green   large     15             3
3   4    red  medium     11             2

In [12]:
# replace with original colum
df["size"]=df["size"].map(order).astype(int)
df

   id  color  size  price  size_encoded
0   1    red     1     10             1
1   2   blue     2     12             2
2   3  green     3     15             3
3   4    red     2     11             2