In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import make_classification, make_moons, make_circles, load_breast_cancer, load_diabetes
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC, SVR
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_squared_error, r2_score

np.random.seed(42)
plt.rcParams['figure.figsize'] = (6, 4)

# Breast Cancer Dataset

In [5]:
cancer= load_breast_cancer()
X =cancer.data
y= cancer.target

print('Feature shape: ',X.shape)
print('Classes: ', cancer.target_names)

Feature shape:  (569, 30)
Classes:  ['malignant' 'benign']

In [6]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=42)

scaler= StandardScaler()
X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled= scaler.transform(X_test)

In [11]:
svc= SVC(kernel='rbf', C=1.0, gamma= 'scale', random_state=42)
svc.fit(X_train_scaled, y_train)

y_pred= svc.predict(X_test_scaled)
acc= accuracy_score(y_test, y_pred)
print('Accuracy with RBF: ', acc)
print('============Classification Report================\n')
print(classification_report(y_test, y_pred))

Accuracy with RBF:  0.9824561403508771
============Classification Report================

              precision    recall  f1-score   support

           0       1.00      0.95      0.98        43
           1       0.97      1.00      0.99        71

    accuracy                           0.98       114
   macro avg       0.99      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

In [12]:
# Confusion matrix
cm= confusion_matrix(y_test, y_pred)
print('Confusion matrix: \n',cm)

Confusion matrix:
 [[41  2]
 [ 0 71]]

In [13]:
def evaluate_svm_c_gamma(X_train, X_test, y_train, y_test, C_values, gamma_values):
    results = []
    for C in C_values:
        for gamma in gamma_values:
            model = SVC(kernel='rbf', C=C, gamma=gamma, random_state=42)
            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)
            acc = accuracy_score(y_test, y_pred)
            results.append({'C': C, 'gamma': gamma, 'accuracy': acc})
    return pd.DataFrame(results)

C_values = [0.1, 1.0, 10.0]
gamma_values = ['scale', 0.01, 0.1, 1.0]

df_hyper = evaluate_svm_c_gamma(X_train_scaled, X_test_scaled,
                                y_train, y_test,
                                C_values, gamma_values)
df_hyper

       C  gamma  accuracy
0    0.1  scale  0.947368
1    0.1   0.01  0.964912
2    0.1    0.1  0.947368
3    0.1    1.0  0.622807
4    1.0  scale  0.982456
5    1.0   0.01  0.964912
6    1.0    0.1  0.964912
7    1.0    1.0  0.631579
8   10.0  scale  0.973684
9   10.0   0.01  0.982456
10  10.0    0.1  0.964912
11  10.0    1.0  0.631579

In [14]:
# Sort by accuracy to see top combinations
df_hyper.sort_values('accuracy', ascending=False)

       C  gamma  accuracy
9   10.0   0.01  0.982456
4    1.0  scale  0.982456
8   10.0  scale  0.973684
1    0.1   0.01  0.964912
10  10.0    0.1  0.964912
6    1.0    0.1  0.964912
5    1.0   0.01  0.964912
0    0.1  scale  0.947368
2    0.1    0.1  0.947368
7    1.0    1.0  0.631579
11  10.0    1.0  0.631579
3    0.1    1.0  0.622807